# Generated by Django 4.1.1 on 2022-09-27 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_category_name_alter_cuisine_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAndRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт блюда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.user', verbose_name='Пользователь')),
            ],
        ),
    ]
