# Generated by Django 4.1.1 on 2022-09-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_userandrecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
    ]
